all content added and styled - ready for trainer review
SlothSan/portfolio pull request #5
Opened 2022-07-12 13:50 UTC by SlothSan

all content added and checked - tested in Firefox / Chrome / Edge. 

Placeholder images in place still for all images.

Cards are using placeholder text / placeholder image. (Does link to the correct live code / github for the JS calculator)

Once reviewed and merged into main - i will work on further styling and animation changes. 

Cheers !

2022-07-12 13:54 UTC, norayna commented on index.html
> +        <nav class="nav-bar"> <!--NavBar goes here-->
the class `nav-bar` is basically the same as `nav` itself - might as well not have the class and just use a tag selector

2022-07-12 13:54 UTC, norayna commented on index.html
> +        <nav class="nav-bar"> <!--NavBar goes here-->
also i think that comment is probably not needed since the `nav` tag and the class both state that this is a nav

2022-07-12 14:00 UTC, norayna commented on index.html
> +        <section id="portfolio" class="portfolio-section"> <!--Portfolio goes here-->
similarly this comment is not needed

2022-07-12 14:05 UTC, SlothSan commented on index.html
> +<head>
Resolved

2022-07-12 14:05 UTC, SlothSan commented on index.html
> +    <link rel="stylesheet" type="text/css" href="./style.css">
Resolved

2022-07-12 14:09 UTC, SlothSan commented on index.html
> +            <div class="links-container"> <!--Navbar flex-end for desktop- space evenly for Mobile.-->
Resolved

2022-07-12 14:09 UTC, SlothSan commented on index.html
> +                <a href="#about" class="nav-button-links"><i class="fa-solid fa-chevron-left nav-icon"></i>About<i class="fa-solid fa-chevron-right nav-icon"></i></a>
Resolved

2022-07-12 14:28 UTC, norayna commented on index.html
> +                <div class="portfolio-intro-container"> <!--Add Chevrons here to make it look like a HTML Tag-->
comment ❌

2022-07-12 15:05 UTC, norayna commented on index.html
> +                    <h2 class="portfolio-title"><i class="fa-solid fa-chevron-left"></i>Mike's Portfolio<i class="fa-solid fa-chevron-right"></i></h2>
would be better to put each new tag on a new line like so:
```html
<h2 class="portfolio-title">
    <i class="fa-solid fa-chevron-left"></i>
    Mike's Portfolio
    <i class="fa-solid fa-chevron-right"></i>
</h2>
```

2022-07-12 15:07 UTC, norayna commented on index.html
> +                <a href="#contact" class="nav-button-links"><i class="fa-solid fa-chevron-left nav-icon"></i>Contact<i class="fa-solid fa-chevron-right nav-icon"></i></a>
put each thing on a new line:
```html
<a href="#contact" class="nav-button-links">
  <i class="fa-solid fa-chevron-left nav-icon"></i>
  Contact
  <i class="fa-solid fa-chevron-right nav-icon"></i>
</a>
```

2022-07-12 15:22 UTC, norayna commented on index.html
> +            <div class="contact-container">
maybe `contact-text-container`?

2022-07-12 15:23 UTC, norayna commented on index.html
> +                <a class="contact-link" href="https://github.com/SlothSan" target="_blank">GitHub <i class="fab fa-github"></i></a>
again better to put everything on a new line

2022-07-12 15:23 UTC, norayna commented on index.html
> +            <footer class="footer-container">
here the class is probably not needed because you can just use `footer` to target it

2022-07-12 15:27 UTC, norayna commented on index.html
> +                <a href="#about" class="scroller-blue"><i class="fa-solid fa-chevron-up fa-5x"></i></a>
`blue` - what if the colour changes in the future? you might also want to reference the fact that it goes back to the top, since there is another blue scroller on the page

2022-07-12 15:35 UTC, norayna commented on index.html
> +                    <div class-="portfolio-container-card-text">
card-text-container

2022-07-12 15:39 UTC, norayna commented on style.css
> +    justify-content: space-between; /* Media query this too use flex-end on desktop */
you probably mean to remove this comment

2022-07-12 15:43 UTC, norayna commented on style.css
> +.nav-icon {
`nav-icon` is not my fav classname for this, because these are more decorations than icons, i would call it maybe something like `nav-chevron` or `nav-bracket`

2022-07-12 15:49 UTC, norayna commented on style.css
> +    margin-top: -100px;
get rid as discussed

2022-07-12 18:57 UTC, SlothSan commented on index.html
> +                <div class="portfolio-intro-container"> <!--Add Chevrons here to make it look like a HTML Tag-->
Resolved

2022-07-12 19:05 UTC, SlothSan commented on index.html
> +            <div class="card-container">
Resolved - moved the CSS to the portfolio-section class and removed the divs.

2022-07-12 19:07 UTC, SlothSan commented on index.html
> +                    <h2 class="portfolio-title"><i class="fa-solid fa-chevron-left"></i>Mike's Portfolio<i class="fa-solid fa-chevron-right"></i></h2>
Resolved made formatting changes to increase readability.

2022-07-12 19:13 UTC, SlothSan commented on index.html
> +            <div class="contact-container">
Resolved.

2022-07-12 19:15 UTC, SlothSan commented on index.html
> +                <a class="contact-link" href="https://github.com/SlothSan" target="_blank">GitHub <i class="fab fa-github"></i></a>
Resolved for all in the contacts-link-container.

2022-07-12 19:15 UTC, SlothSan commented on index.html
> +                <a class="contact-link" href="tel:+447951068115">Call me <i class="fas fa-mobile-alt"></i></a>
Resolved

2022-07-12 19:18 UTC, SlothSan commented on index.html
> +                <a class="contact-link" href="tel:+447951068115">Call me <i class="fas fa-mobile-alt"></i></a>
Also did all the scroller chevrons.

2022-07-12 19:18 UTC, SlothSan commented on index.html
> +            <footer class="footer-container">
Resolved - removed class and changed CSS to use footer not that class.

2022-07-12 19:29 UTC, SlothSan commented on index.html
> +                            <a href="https://github.com/SlothSan/odin-calculator" target="_blank" class="portfolio-card-link">View on <i class="fa-brands fa-github fa-spin-hover"></i></a>
Changes made on 1 card and copied to other placeholder cards - resolved.

2022-07-12 19:31 UTC, SlothSan commented on index.html
> +                    <div class-="portfolio-container-card-text">
Resolved - updated and CSS changed.

2022-07-12 19:31 UTC, SlothSan commented on index.html
> +                            <a href="https://github.com/SlothSan/odin-calculator" target="_blank" class="portfolio-card-link">View on <i class="fa-brands fa-github fa-spin-hover"></i></a>
Resolved.

2022-07-12 19:42 UTC, SlothSan commented on style.css
> +.nav-icon {
Resolved - CSS & HTML class names changed and tested.

2022-07-12 19:43 UTC, SlothSan commented on style.css
> +    margin-top: -100px;
Resolved removed as it in fact did nothing.

2022-07-13 08:04 UTC, norayna requested changes
checkpoint

2022-07-13 08:05 UTC, norayna commented on index.html
> +                <div class-="card-text-container">
a rogue minus on this line

2022-07-13 08:11 UTC, norayna requested changes
waiting for all the changes then will review again

2022-07-13 08:26 UTC, SlothSan commented on index.html
> +                <div class-="card-text-container">
Removed "-" on all lines this effected. - Resolved.

2022-07-13 11:20 UTC, SlothSan commented
This is ready to be reviewed to push to main (hopefully!).

All further changes i will do on inProgress but happy with this as is, just needs more styling and animations and the cool stuff.

2022-07-13 11:21 UTC, SlothSan commented on index.html
> -                        <a href="https://slothsan.github.io/odin-calculator/" target="_blank" class="portfolio-card-link">
Removed this as its pointless as you are in-fact on the live site.

2022-07-14 15:43 UTC, norayna approved these changes
approveddddddd

2022-07-14 15:47 UTC, merged